server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_cart_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    persist-authorization: true
    try-it-out-enabled: true